Repository Maanna-zan/Maanna-zan_FE, pull requests merged in 2023-05, with the labels that each got.

#287 [style]모달창 style 및 모달포털페이지 달력제거 및 위치조정
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
Labels: style

#288 아이디 찾기 기능 추가
  public/Group 2066.png
  src/components/Atoms/Input.jsx
  src/components/Modals/SignInModal.jsx
  src/components/Modals/SignInPortalExample.jsx
  src/components/Modals/SignUpModal.jsx
  src/components/Modals/SignUpPortalExample.jsx
  src/components/Molecules/LinkToNav.jsx
Labels: feat

#294 핸들러 모르고 다른 것 지움
  src/components/Modals/SignInModal.jsx
Labels: fix

#296 [style][feat]SearchKeywordModal.jsx,
  src/components/Modals/SearchKeywordModal.jsx
  src/features/map/MapBeginning.js
  src/features/map/MapMidPoint.js
Labels: style, feat

#298 [fix] 카테고리 버튼 여러번 클릭해야 값 나오는 부분 수정.
  src/features/map/MapMidPoint.js
Labels: fix

#302 295 fix edit
  README.md
  src/components/Atoms/SEO/SeoLayout.jsx
  src/components/Molecules/LinkToNav.jsx
  src/features/AddReComment.js
  src/features/CommentsList.js
  src/features/ReCommentList.js
  src/features/mypage/Calender.js
  src/features/mypage/Log.js
Labels: style, fix

#303 [feat][style] MapMidPoint페이지 뒤로가기 버튼 구현 및 CSS
  src/features/map/MapMidPoint.js
Labels: style, feat

#305 [fix]SearchKeywordModalPortal.jsx 파일 버그 수정
  src/components/Modals/SearchKeywordModalPortal.jsx
Labels: fix

#307 [style][fix] SearchKeywordModal.jsx 파일
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
Labels: style, fix

#310 콘솔로그 주석처리
  src/components/Modals/SettingModal.jsx
  src/components/Modals/SettingPortalExample.jsx
  src/components/Modals/SignInModal.jsx
  src/components/Modals/SignUpModal.jsx
  src/components/Molecules/LinkToNav.jsx
  src/components/Templates/mainpage/MainFirstSection.jsx
  src/features/AddComment.js
  src/features/AddReComment.js
  src/features/CommentsList.js
  src/features/ReCommentList.js
  src/features/mypage/Log.js
  src/features/mypage/MyWritePost.js
  src/features/mypage/Save.js
  src/features/post/CommunityList.jsx
  src/features/post/Post.jsx
  src/pages/OAuth/index.js
  src/pages/mypage/changenick.js
  src/pages/mypage/changepw.js
  src/pages/mypage/index.js
  src/pages/searchpassword.js
Labels: style, feat, fix

#312 [feat][style]SearchKeywordModalPortal.jsx에서 출발지 값
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapMidPoint.js
Labels: style, feat

#315 로그인 문제 해결
  src/components/Modals/SignInModal.jsx
  src/components/Molecules/LinkToNav.jsx
  src/features/mypage/GetMyAlcohols.js
  src/features/mypage/GetmyPost.js
  src/pages/_app.js
Labels: fix

#317 [feat][style]MapMidPoint.js파일 기능추가
  src/features/map/MapMidPoint.js
Labels: style, feat

#319 [fix]중간위치찾기 버튼 클릭시 버그 해결.
  src/components/Modals/SearchKeywordModalPortal.jsx
Labels: fix

#321 맵어포인트먼트 로그인 전 후 페이지 만들기
  package.json
  src/components/Modals/SignInModal.jsx
  src/features/kakaoLogin/KakaoLogIn.js
  src/features/map/MapAppointment.js
  src/features/map/MapBeginning.js
  src/features/mypage/GetMyAlcohols.js
  src/features/mypage/GetmyPost.js
  src/features/mypage/MyWritePost.js
  src/hook/alcohol/useGetStore.js
  src/pages/mapmidpoint/index.js
  src/pages/test/index.js
  yarn.lock
Labels: feat

#323 약속잡기에 날짜 값 들어가게 조정
  src/features/map/MapAppointment.js
Labels: feat

#325 [feat][style]중간위치술집 검색 카테고리 추가(오뎅바는 주석처리).
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapMidPoint.js
Labels: style, feat

#327 약속잡기 모달창 및 링크에 href
  public/Image1.png
  src/components/Atoms/Button.jsx
  src/components/Modals/AppointmentModal.jsx
  src/components/Modals/AppointmentPortalExample copy.jsx
  src/features/map/MapAppointment.js
  src/pages/alcohols/[id].js
Labels: feat, fix

#329 [feat]약속만들기 페이지 feat (선택장소props 전달필요)
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapAppointment.js
  src/features/map/MapMidPoint.js
Labels: feat

#331 설문조사 링크 추가
  src/components/Molecules/LinkToNav.jsx
Labels: feat, fix

#334 커서 포인터 , 네비게이션 바 수정
  src/components/Atoms/CloseBtn.jsx
  src/components/Modals/SignInModal.jsx
  src/components/Molecules/LinkToNav.jsx
  src/components/Templates/mainpage/MainFirstSection.jsx
  src/features/mypage/MyWritePost.js
  src/pages/mypage/index.js
Labels: fix

#335 [fix]배포 전 수정
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapAppointment.js
  src/features/map/MapMidPoint.js
  src/pages/mapmidpoint/index.js
Labels: fix

#337 배포전 수정
  src/features/mypage/MyWritePost.js
  src/pages/community/[id].js
Labels: fix

#343 342- 로그인 회원가입 수정사항 조정
  src/components/Modals/SignInModal.jsx
  src/components/Modals/SignUpModal.jsx
  src/components/Modals/SignUpPortalExample.jsx
  src/components/Molecules/LinkToNav.jsx
Labels: fix

#346 유저 경험 바탕 기능 fix
  src/components/Modals/SettingModal.jsx
  src/components/Modals/SettingPortalExample.jsx
  src/components/Modals/SignInModal.jsx
  src/components/Modals/SignUpModal.jsx
  src/components/Molecules/LinkToNav.jsx
  src/components/Organisms/Footer.jsx
  src/features/mypage/GetMyAlcohols.js
  src/features/mypage/GetmyPost.js
  src/features/mypage/MyWritePost.js
  src/pages/mypage/index.js
Labels: style, feat, fix

#348 [fix]SearchKeywordModalPortal.jsx 지도 출발지 마커 버그 해결
  src/components/Modals/SearchKeywordModalPortal.jsx
Labels: fix

#349 347 fix find email
  src/components/Atoms/Input.jsx
  src/components/Modals/SettingModal.jsx
  src/components/Modals/SignInModal.jsx
  src/components/Modals/SignUpModal.jsx
  src/features/AddReComment.js
  src/features/CommentsList.js
  src/features/ReCommentList.js
  src/features/mypage/EventForm.js
  src/features/mypage/GetMyAlcohols.js
  src/features/mypage/GetmyPost.js
  src/features/mypage/Log.js
  src/features/mypage/MyWritePost.js
  src/pages/OAuth/index.js
  src/pages/index.js
Labels: style, feat, fix

#351 콘솔 제거
  src/components/Modals/SettingModal.jsx
  src/features/kakaoLogin/KakaoButton.js
  src/features/mypage/GetMyAlcohols.js
  src/features/mypage/GetmyPost.js
  src/features/mypage/Log.js
Labels: fix

#353 전반적인 수정사항
  src/components/Modals/SettingModal.jsx
  src/components/Modals/SignInModal.jsx
  src/components/Modals/SignUpModal.jsx
  src/components/Molecules/LinkToNav.jsx
  src/components/Templates/mainpage/MainFirstSection.jsx
  src/features/mypage/EventForm.js
  src/hook/useConfirm.js
  src/pages/mypage/index.js
Labels: style, feat, fix

#357 건의사항 수정
  public/Group 2559.png
  src/components/Modals/SettingModal.jsx
  src/components/Modals/SignInModal.jsx
  src/components/Modals/SignUpModal.jsx
  src/components/Molecules/LinkToNav.jsx
  src/components/Templates/withoutToken/NoToken.jsx
  src/features/AddComment.js
  src/features/CommentsList.js
  src/features/ReCommentList.js
  src/features/mypage/EventForm.js
  src/features/mypage/GetMyAlcohols.js
  src/features/mypage/GetmyPost.js
  src/features/mypage/Log.js
  src/features/mypage/MyWritePost.js
  src/pages/mypage/index.js
  src/shared/instance.js
Labels: style, feat, fix

#360 [feat][style] MapMidPoint.js에서 장소데이터 Props보내줌.
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapAppointment.js
  src/features/map/MapMidPoint.js
Labels: style, feat

#365 [style] 지도 및 전체적인 포지션, 비율 등 조절.
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/components/Templates/mainpage/MainLastSectionMovie.jsx
  src/components/Templates/mainpage/MainSecondSection.jsx
  src/features/map/MapAppointment.js
  src/features/map/MapBeginning.js
  src/features/map/MapMidPoint.js
Labels: style

#370 [fix][style]중간위치 찾기 후에도 출발지 변경 가능하도록 수정.
  src/components/Modals/SearchKeywordModalPortal.jsx
Labels: style, fix

#373 [style][fix] 디테일 CSS
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapAppointment.js
  src/features/map/MapMidPoint.js
Labels: style, fix

#375 회원가입 이메일 인증추가
  src/components/Modals/SignInModal.jsx
  src/components/Modals/SignUpModal.jsx
  src/features/mypage/Log.js
  src/hook/useConfirm.js
Labels: feat, fix

#376 [feat]MapAppointment.js 페이지 약속잡기 서버 통신
  src/features/map/MapAppointment.js
  src/features/map/tempCodeRunnerFile.js
Labels: feat

#379 [feat]중간지점 에러시 새로고침해도 계속 에러나는 부분 기능추가
  src/features/map/MapMidPoint.js
Labels: feat

#384 약속만들기 조회 (지도빼고 완료)
  src/components/Atoms/Button.jsx
  src/components/Atoms/TrashButton.jsx
  src/features/mypage/EventForm.js
  src/features/mypage/Log.js
  src/features/mypage/LogMeet.js
  src/features/mypage/LogMyDay.js
Labels: style, feat, fix, refactor

#386 빌드 에러 수정
  src/components/Modals/SignInModal.jsx
  src/pages/OAuth/Kakao.js
  src/pages/OAuth/index.js
Labels: fix

#388 [fix] build 배포 에러 해결(/test에서 MapAppointment 임포트삭제)
  src/pages/test/index.js
Labels: fix

#391 [style]CSS수정
  public/MoveBackButtonIcon.png
  public/UnlogedInImg.png
  src/components/Atoms/Button.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapAppointment.js
  src/features/map/MapMidPoint.js
  src/features/map/tempCodeRunnerFile.js
Labels: style

#393 [feat]모달창 바깥쪽 눌렀을때 모달 닫히는 기능
  src/components/Modals/SearchKeywordModal.jsx
Labels: feat

#396 [fix] MapAppoinment.js에서 SelectedDate값 밀리는 버그 해결.
  src/features/map/MapAppointment.js
Labels: fix

#398 397 fixsomeerror
  src/components/Modals/Pagenation2.js
  src/components/Modals/SettingModal.jsx
  src/components/Modals/SignUpModal.jsx
  src/components/Molecules/LinkToNav.jsx
  src/features/mypage/LogMeet.js
  src/features/mypage/LogMyDay.js
Labels: feat, fix

#399 [style]SearchKeywordModal.jsx : 장소 리스트 CSS 및 클릭시 디자인
  src/components/Modals/SearchKeywordModal.jsx
Labels: style

#404 [fix]MapAppointmet.js파일 Syntax Error해결.
  src/features/map/MapAppointment.js
Labels: fix

#405 [style]MapMidPoint.js 파일 CSS
  public/CategorySlideDirection.png
  public/RedBottomDirection.png
  public/heartButton.png
  public/shareButton.png
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapMidPoint.js
Labels: style

#407 [style]SearchKeywordModalPortal.jsx, MapMidPoint.js CSS
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapMidPoint.js
Labels: style

#408 392 featdellogmeet
  src/components/Atoms/CalenderLogIcon.jsx
  src/components/Atoms/TrashButton.jsx
  src/components/Modals/LogMyDayDetailModal.jsx
  src/components/Modals/SearchKeywordModal.jsx
  src/features/map/MapAppointment.js
  src/features/mypage/EventForm.js
  src/features/mypage/Log.js
  src/features/mypage/LogMeet.js
  src/features/mypage/LogMyDay.js
  src/hook/alcohol/useGetStore.js
  src/pages/community/[id].js
  src/shared/instance.js
Labels: feat, fix

#410 html 부분에 닫는 태그 에러
  src/features/mypage/LogMeet.js
Labels: feat, fix

#413 [fix]배포오류해결(MapAppointment.js syntax error)
  src/features/map/MapAppointment.js
Labels: fix

#415 [style]map관련 페이지 위치 및 높이,넓이 수정
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapMidPoint.js
Labels: style

#419 콘솔로그제거
  src/features/mypage/GetmyPost.js
  src/features/mypage/Log.js
  src/features/mypage/LogMeet.js
Labels: fix

#422 약속 공유
  src/features/mypage/LogMeet.js
Labels: feat

#424 쉐어버튼 수정 및 네비게이션 nav태그 속 div 태그 제거
  src/components/Molecules/LinkToNav.jsx
  src/features/mypage/LogMeet.js
Labels: feat, fix

#425 [fix]alcohols 페이지 [id].js 지도 부분 로딩 오류로 수정
  src/pages/alcohols/[id].js
Labels: fix

#432 공유버튼 되돌리기
  src/features/mypage/LogMeet.js
Labels: fix

#441 댓글 crud 수정
  src/features/CommentsList.js
Labels: fix

#446 디테일 사항 반영 수정
  src/components/Molecules/LinkToNav.jsx
  src/features/AddComment.js
  src/features/AddReComment.js
  src/pages/alcohols/[id].js
Labels: fix

#449 [fix][style] MapMidPoint.js파일, MapAppointment.js파일 스타일 수정
  src/features/map/MapAppointment.js
  src/features/map/MapMidPoint.js
Labels: style, fix

#450 [fix][refactor]MapMidPoint 코드 리팩토링 및 지도 관련 파일 코드정리
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapAppointment.js
  src/features/map/MapBeginning.js
  src/features/map/MapMidPoint.js
Labels: fix, refactor

#453 [docs]READEME.md 수정
  README.md
Labels: documentation

#454 비밀번호 찾기 후 로그인시 404에러 문제 해결
  src/pages/oauth.js
Labels: fix

#457 [style] MapMidPoint.js 및 메인페이지 CSS 수정,
  src/features/map/MapAppointment.js
  src/features/map/MapMidPoint.js
  src/pages/index.js
Labels: style
