Repository Maanna-zan/Maanna-zan_FE, pull requests merged in 2023-04, with the labels that each got.

#55 [feat]회원 탈퇴 기능 미완 .내가 좋아요한 게시글 기능 구현 완료.
  next.config.js
  package.json
  public/Group 2041.png
  public/mypageQuestion.png
  src/components/Modals/Modal.jsx
  src/components/Modals/SettingModal.jsx
  src/components/Modals/SettingPortalExample.jsx
  src/components/Molecules/LinkToNav.jsx
  src/features/mypage/FindPost.js
  src/features/mypage/Log.js
  src/features/mypage/Save.js
  src/features/mypage/react-calender.module.css
  src/pages/mypage/changenick.js
  src/pages/mypage/index.js
  yarn.lock
Labels: feat

#56 [Fix] 사이거리 중간 값 좌표 받기, 버그 수정 및 중간 위치 마커 이미지 변경
  README.md
  public/MaannajanLogo.png
  src/pages/map/index.js
Labels: fix

#61 [feat] 메인페이지2(기본상태) 생성
  src/features/map/MapBeginning.js
  src/pages/mapBegin/index.js
Labels: feat

#66 [feat] MapBeginning.js 파일 기능 구현 완료.
  src/features/map/MapBeginning.js
Labels: feat

#69 [style] map 페이지 index.js 파일 수정.
  src/pages/map/index.js
Labels: style

#72 마이페이지 css 조정 #57
  public/Group 1972.png
  public/Group 2000.png
  src/components/Modals/Modal.jsx
  src/components/Modals/SettingModal.jsx
  src/components/Modals/SettingPortalExample.jsx
  src/components/Modals/SignUpModal.jsx
  src/features/mypage/FindPost.js
  src/features/mypage/Log.js
  src/features/mypage/Save.js
  src/features/mypage/react-calender.module.css
  src/pages/mypage/index.js
  yarn.lock
Labels: style

#73 [feat] AddingInputBoxButton 기능 구현.
  src/features/map/AddingInputBoxButton.js
  src/pages/map/index.js
Labels: feat

#74 [feat] map페이지 모달창(키워드검색위한) 기본 기능 구현.
  src/components/Modals/SearchKeywordModal.jsx
  src/features/map/AddingInputBoxButton.js
  yarn.lock
Labels: feat

#77 [feat][style]
  src/components/Modals/SearchKeywordModal.jsx
Labels: style, feat

#80 설정 모달 css
  src/components/Atoms/SEO/HeadInfo.jsx
  src/components/Modals/SettingModal.jsx
  src/components/Modals/SignInModal.jsx
  src/components/Modals/SignInPortalExample.jsx
  src/components/Modals/SignUpPortalExample.jsx
  src/components/Molecules/LinkToNav.jsx
Labels: style

#81 회원 탈퇴기능 구현 -> 좋아요 한 게시물 없어야 아직 탈퇴가능
  src/components/Modals/SettingModal.jsx
  src/features/mypage/Save.js
Labels: feat, fix

#83 로그인 모달 css 수정 및 정리
  src/components/Modals/SignInModal.jsx
Labels: style, fix

#87 84 fix find password
  src/components/Modals/SignInModal.jsx
Labels: feat, fix

#89 [feat][fix] 모달창 키워드 검색 로직 구현 및 버그 수정
  src/components/Modals/SearchKeywordModal.jsx
  src/features/map/AddingInputBoxButton.js
  src/features/map/MapBeginning.js
Labels: feat, fix

#91 회원가입 css 수정
  src/components/Modals/SignUpModal.jsx
Labels: style, fix

#95 Footer 기능 구현 및 전역 설정 완료
  public/Group 1893.png
  src/components/Atoms/SEO/SeoLayout.jsx
  src/components/Organisms/Footer.jsx
Labels: style, feat

#96 [feat][style] 키워드검색 모달창 뷰화면 구성 및 기본 CSS
  src/components/Modals/SearchKeywordModal.jsx
Labels: style, feat

#107 [feat][style]키워드검색 value 저장 및 리스트 클릭 시 CSS 수정.
  src/components/Modals/SearchKeywordModal.jsx
  src/features/map/AddingInputBoxButton.js
  src/pages/signup.js
Labels: style, feat

#110 [fix]배포중 오류 해결.
  src/pages/signup.js
Labels: fix

#116 instance 에러 수정
  src/shared/instance.js
Labels: style, fix

#118 401 에러 처리
  src/components/Molecules/LinkToNav.jsx
Labels: fix

#120 네비 바 오류 해결
  src/components/Molecules/LinkToNav.jsx
Labels: style, fix

#124 [fix]서버 배포위한 환경변수 수정
  src/pages/_document.js
Labels: fix

#127 125 feat change password
  src/components/Modals/SettingModal.jsx
  src/features/mypage/Save.js
Labels: feat

#134 133 fixnav
  src/components/Molecules/LinkToNav.jsx
Labels: fix

#136 내가 작성한 글 보기 기능 구현 및 CSS 완료
  public/Group 2017.png
  public/Group 2041.png
  public/mypageQuestion.png
  src/features/mypage/FindPost.js
  src/features/mypage/Log.js
  src/features/mypage/MyWritePost.js
  src/pages/mypage/index.js
Labels: style, fix

#141 날라간 코드 업로드
  src/components/Atoms/Button.jsx
  src/features/mypage/FindPost.js
Labels: fix

#145 [feat]모달창 props 값을 부모컴포넌트에서 꺼내어 input의 value 활용
  src/features/map/AddingInputBoxButton.js
Labels: feat

#147 [fix] 각각의 인풋에 각각의 value값 지정
  src/features/map/AddingInputBoxButton.js
Labels: fix

#149 [feat] 모달창props값 백서버 request 폼으로 가공 로직
  src/features/map/AddingInputBoxButton.js
Labels: feat

#151 [feat]props로 받은 가동된 데이터로 서버통신 로직 구현
  src/features/map/AddingInputBoxButton.js
Labels: feat

#154 잔 오류 수정
  src/components/Modals/SignUpModal.jsx
  src/features/mypage/GetMyAlcohols.js
  src/features/mypage/MyWritePost.js
  src/features/signUpAlert/BirthAlert.js
  src/features/signUpAlert/EmailAlert.js
  src/features/signUpAlert/NickNameAlert.js
  src/features/signUpAlert/PasswordAlert.js
  src/features/signUpAlert/PhoneNumberAlert.js
  src/features/signUpAlert/UserNameAlert.js
  src/pages/mypage/index.js
Labels: fix

#156 [feat][fix]props가져온 값들로 지도에 마커찍기
  src/features/map/AddingInputBoxButton.js
  src/pages/map/index.js
Labels: feat, fix

#158 [fix]지도 중간값 받아오기 통신 에러 해결 코드 수정.
  src/features/map/AddingInputBoxButton.js
Labels: fix

#159 닉네임 로컬스토리지와 쿠키에 저장 , 로그아웃 버튼 누르면 전부 삭제 되도록 구현 완료
  src/components/Modals/SignInModal.jsx
  src/components/Molecules/LinkToNav.jsx
Labels: feat

#161 자신의 댓글에만 변형이 가능하도록 구현 완료
  src/features/CommentsList.js
Labels: feat

#163 [fix] 중간위치값 받기위하여 서버통신시 잘못된 값 Request 가는 부분 수정
  src/features/map/AddingInputBoxButton.js
Labels: fix

#165 [fix]서버Request주는 위도경도값 뒤바뀐거 코드 수정.
  src/features/map/AddingInputBoxButton.js
Labels: fix

#167 [fix]서버Request주는 위도경도값 뒤바뀐거 코드 수정2
  src/features/map/AddingInputBoxButton.js
Labels: fix

#176 네비게이션 수정
  src/components/Molecules/LinkToNav.jsx
Labels: style, fix

#177 [fix]전달 받은 값 장소 마커 여러개 찍기 실패.
  src/features/map/AddingInputBoxButton.js
Labels: fix

#179 [style]map 페이지 index.js 파일 수정 및 코드정리
  src/pages/map/index.js
Labels: style

#183 [feat][style] main페이지 2번째 스크롤 페이지 구현 및 CSS
  public/mainPageSecondScroll.png
  public/mainPageSecondScrolldeIcon.png
  src/components/Atoms/imgWrapper.jsx
  src/components/Templates/mainpage/MainSecondSection.jsx
  src/features/map/MapBeginning.js
  src/pages/mapBegin/index.js
Labels: style, feat

#187 [style]SearchKeywordModal.jsx파일 style
  src/components/Modals/SearchKeywordModal.jsx
Labels: style

#201 [feat]중간지점 마커 찍은 후 지도이동 기능 구현
  src/features/map/AddingInputBoxButton.js
Labels: feat

#203 [feat]중간지점 마커 후 지도이동 기능(AddingInputBoxButton.js)
  src/features/map/AddingInputBoxButton.js
Labels: feat

#205 [feat] 중간지점 마커 후 지도 이동(AddingInputBoxButton.js)
  src/features/map/AddingInputBoxButton.js
Labels: feat

#207 [feat]중간지점 마커 후 지도 이동 기능 구현 성공
  src/features/map/AddingInputBoxButton.js
Labels: feat

#212 [fix]AddingInputBoxButton.js의 헤더에 토큰 제거
  src/features/map/AddingInputBoxButton.js
Labels: fix

#214 [refactor]AddingInputBoxButton.js파일 폴더 이동 및 Rename.
  src/components/Modals/SearchKeywordModal.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapBeginning.js
  src/pages/map/index.js
Labels: help wanted, refactor

#218 [feat] kakaoApi (중간 위치 검색 값 DB저장 및 불러오기) 서버통신
  src/features/map/MapMidPoint.js
Labels: feat

#220 카카오 로그인 일부 구현
  public/Group 2383.png
  src/components/Modals/SignInModal.jsx
  src/features/kakaoLogin/KakaoButton.js
  src/features/kakaoLogin/KakaoLogIn.js
  src/pages/oauth.js
Labels: feat

#222 카카오 소셜 로그인 인가 api로 보내기
  src/pages/oauth.js
Labels: feat

#224 리다이렉트 url 변경
  src/features/kakaoLogin/KakaoLogIn.js
Labels: fix

#228 카카오 로그인 오류 수정중
  src/features/kakaoLogin/KakaoButton.js
  src/features/kakaoLogin/KakaoLogIn.js
  src/pages/OAuth/Kakao.js
  src/pages/OAuth/index.js
  src/pages/oauth.js
Labels: fix

#231 227 fix kakao login
  src/components/Modals/SignInModal.jsx
  src/features/kakaoLogin/KakaoButton.js
  src/features/kakaoLogin/KakaoLogIn.js
  src/pages/OAuth/Kakao.js
  src/pages/oauth.js
Labels: fix

#233 캘린더 get 이랑 post 준비 완료
  src/features/mypage/Calender.js
  src/features/mypage/EventForm.js
  src/features/mypage/Log.js
Labels: feat

#237 [fix]MapMidPoint.js, SearchKeywordModalPortal.jsx 파일
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/features/map/MapMidPoint.js
Labels: fix

#239 [feat]지도 생성 및 중간위치좌표 props받은 값으로 지도 마커찍기.
  src/features/map/MapMidPoint.js
  src/pages/_document.js
Labels: feat

#242 [feat] 지도생성 및 중간지점 주변 술집 마커 및 리스트 나타내기 구현.
  src/components/Modals/SearchKeywordModal.jsx
  src/features/map/MapMidPoint.js
Labels: feat

#243 캘린더 입력 및 조회 , 페이지네이션
  src/components/Modals/Pagenation2.js
  src/components/Modals/chunk.js
  src/features/mypage/Calender.js
  src/features/mypage/Log.js
Labels: feat

#247 오류사항 수정
  public/Group 2248.png
  src/features/mypage/Log.js
Labels: fix

#249 [fix] 모달창 검색 버튼 2번 눌러야 검색 되는 버그 해결.
  src/components/Modals/SearchKeywordModal.jsx
Labels: fix

#255 캘린더 css
  src/features/mypage/EventForm.js
  src/features/mypage/Log.js
Labels: style

#257 개인ㄷ적인 도큐먼트파일 오류 해결
  src/pages/_document.js
Labels: fix

#259 비밀번호 변경
  public/Group 2521.png
  src/components/Modals/SignInModal.jsx
  src/pages/OAuth/index.js
Labels: feat

#265 264 style calender
  src/features/mypage/Log.js
  src/pages/mypage/index.js
Labels: style, feat

#267 페이지네이션
  src/features/mypage/GetMyAlcohols.js
  src/features/mypage/GetmyPost.js
  src/features/mypage/MyWritePost.js
  src/pages/mypage/index.js
Labels: style, fix

#269 푸터 수정 완료
  src/components/Organisms/Footer.jsx
Labels: fix

#271 달력 구현 완료
  src/components/Modals/SearchKeywordModalPortal.jsx
Labels: feat

#276 [style]SearchKeywordModalPortal.jsx 파일 CSS
  public/ModalPortalAddInputPlus.png
  public/ModalPortalInputXButton.png
  public/ModalPortalSearchBarIcon.png
  src/components/Atoms/Wrapper.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
Labels: style

#278 [feat]onInputClearHandler
  src/components/Modals/SearchKeywordModalPortal.jsx
Labels: feat

#281 [style][refactor]searchKeywordModalPortal.jsx파일 CSS
  src/components/Atoms/Flex.jsx
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/components/Themes/theme.js
Labels: style, refactor

#283 [feat][style][id.]j파일 지도 넣기 및 마커변경(현재 커스터마이징 마커 이미지 깨져서 나옴)
  public/MarkerIMG.png
  src/components/Modals/SearchKeywordModalPortal.jsx
  src/pages/alcohols/[id].js
Labels: style, feat
